version: '3'
services:
  
  backend:
    build:
      context: .
      image: zeelpatel7610/devops-project_backend:latest
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: myDb
    depends_on:
      - mysql
