apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-project
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    repoURL: 'https://github.com/ZeelPatel18/DevOps-Project.git'
    path: 'helm/'   # Path within the Git repositor
    targetRevision: HEAD
    helm:
      valueFiles:
        - helm/mysql-chart/values.yaml
        - helm/flask-app-chart/values.yaml
    directory:
      recurse: true   # Recursively search for Helm charts in subdirectories
  syncPolicy:
    automated:
      selfHeal: true   # Automatically reapply manifests on changes

